# This is a basic workflow to help you get started with Actions

name: Check if version.txt has been updated.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch. Exclude when changes are to documentation or CI files only.
  pull_request:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Check for version_latest.txt update"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

       - name: Check for Changed Files
         uses: brettcannon/check-for-changed-files@v1.1.0
         with:
           file-pattern: version_latest.txt
           failure-message: "You have not updated version_latest.txt. This is a required file to update at each PR. Please sync your latest changes and update the version number."

       - name: Prevent changes to workflow files
         uses: DovnarAlexander/github-action-file-detection@v0.3.0
         with:
    # Find-like wildcard to find files\directories.
           wildcard: ".github/workflows/*.yml"
    # Type of find command. Supported values: f (file), d (directory), l (link), p (pipe), s (socket).
    # Exit code for non-empty find result.
           exit_code_found: 1
    # Exit code for empty find result.
           exit_code_not_found: 0
